spring:
  application:
    name: expensetracker

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/expense_tracker}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  server:
  port: ${PORT:8080}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false   # turn off noisy SQL logs in cloud

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME:ExpTrackerBot}
