spring:
  application:
    name: expensetracker

  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: IyAyUCVfZjfASuHLgsEYFrXwAztprSMY
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false   # turn off noisy SQL logs in cloud

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

telegram:
  bot:
    token: 8570313330:AAG8dvnYFsPTw52V57LKtxFIA6QUGOAmbsM
    username: ExpTrackerBot
